# サンプルデータを生成する関数群


#' Generate sample data for Direct LiNGAM
#'
#' Generates a sample dataset with a known causal structure for testing
#' and demonstrating Direct LiNGAM. The true causal structure is:
#'
#' x3 -> x0 (coef = 3.0)
#' x3 -> x2 (coef = 6.0)
#' x0 -> x1 (coef = 3.0)
#' x2 -> x1 (coef = 2.0)
#' x0 -> x5 (coef = 4.0)
#' x0 -> x4 (coef = 8.0)
#' x2 -> x4 (coef = -1.0)
#'
#' @param n number of samples (default: 1000)
#' @param seed random seed (default: 42)
#' @return data.frame with columns x0, x1, x2, x3, x4, x5
#'
#' @examples
#' X <- generate_lingam_sample_6(n = 1000, seed = 42)
#' head(X)
#' result <- direct_lingam(X)
#' result$causal_order
#'
#' @export
generate_lingam_sample_6 <- function(n = 1000L, seed = 42L) {

  # --- Input validation ---
  if (!is.numeric(n) || n < 2) stop("n must be an integer >= 2.")
  if (!is.numeric(seed))       stop("seed must be numeric.")

  n    <- as.integer(n)
  seed <- as.integer(seed)

  # --- Error terms（各変数に独立した乱数シードを設定）---
  set.seed(seed)     ; e0 <- runif(n)
  set.seed(seed + 1L); e1 <- runif(n)
  set.seed(seed + 2L); e2 <- runif(n)
  set.seed(seed + 3L); e3 <- runif(n)
  set.seed(seed + 4L); e4 <- runif(n)
  set.seed(seed + 5L); e5 <- runif(n)

  # --- Data generation（因果順序に従う）---
  x3 <- e3
  x0 <- 3.0 * x3 + e0
  x2 <- 6.0 * x3 + e2
  x1 <- 3.0 * x0 + 2.0 * x2 + e1
  x5 <- 4.0 * x0 + e5
  x4 <- 8.0 * x0 - 1.0 * x2 + e4

  return(
    data.frame(x0 = x0, x1 = x1, x2 = x2,
               x3 = x3, x4 = x4, x5 = x5)
    )
}


#' True adjacency matrix for 6-variable sample
#'
#' Returns the true adjacency matrix corresponding to the data
#' generated by generate_lingam_sample_6().
#'
#' True causal structure:
#'   x3 -> x0 (coef =  3.0)
#'   x3 -> x2 (coef =  6.0)
#'   x0 -> x1 (coef =  3.0)
#'   x2 -> x1 (coef =  2.0)
#'   x0 -> x5 (coef =  4.0)
#'   x0 -> x4 (coef =  8.0)
#'   x2 -> x4 (coef = -1.0)
#'
#' @param labels variable names (default: x0-x5)
#' @return true adjacency matrix (6 x 6)
#'
#' @examples
#' m <- true_adjacency_matrix_6()
#' print(m)
#'
#' # Use with generate_lingam_sample_6()
#' X <- generate_lingam_sample_6()
#' result <- direct_lingam(X)
#' B_hat <- result$adjacency_matrix
#' colnames(B_hat) <- rownames(B_hat) <- colnames(X)
#' B_hat
#' @export
true_adjacency_matrix_6 <- function(labels = paste0("x", 0:5)) {

  if (length(labels) != 6) {
    stop("labels must be a character vector of length 6.")
  }

  m <- matrix(0, nrow = 6, ncol = 6,
              dimnames = list(labels, labels))

  # [row = to, col = from] = coefficient
  m["x0", "x3"] <-  3.0
  m["x2", "x3"] <-  6.0
  m["x1", "x0"] <-  3.0
  m["x1", "x2"] <-  2.0
  m["x5", "x0"] <-  4.0
  m["x4", "x0"] <-  8.0
  m["x4", "x2"] <- -1.0

  return(m)
}


#' Generate 10-variable sample data for Direct LiNGAM
#'
#' Generates a sample dataset with a known causal structure for testing
#' and demonstrating Direct LiNGAM. The true causal structure is:
#'
#' x3 -> x0 (coef =  3.0)
#' x3 -> x2 (coef =  6.0)
#' x3 -> x9 (coef =  7.0)
#' x0 -> x1 (coef =  3.0)
#' x0 -> x5 (coef =  4.0)
#' x0 -> x4 (coef =  8.0)
#' x0 -> x7 (coef =  3.0)
#' x2 -> x1 (coef =  2.0)
#' x2 -> x4 (coef = -1.0)
#' x2 -> x8 (coef =  0.5)
#' x1 -> x6 (coef =  2.0)
#' x1 -> x9 (coef =  1.0)
#' x5 -> x8 (coef =  2.0)
#' x4 -> x7 (coef =  1.5)
#' x6 -> x9 (coef =  1.0)
#'
#' @param n number of samples (default: 1000)
#' @param seed random seed (default: 42)
#' @return data.frame with columns x0-x9
#'
#' @examples
#' X <- generate_lingam_sample_10(n = 1000, seed = 42)
#' head(X)
#' result <- direct_lingam(as.matrix(X))
#' result$causal_order
#'
#' @export
generate_lingam_sample_10 <- function(n = 1000L, seed = 42L) {

  # --- Input validation ---
  if (!is.numeric(n) || n < 2) stop("n must be an integer >= 2.")
  if (!is.numeric(seed))       stop("seed must be numeric.")

  n    <- as.integer(n)
  seed <- as.integer(seed)

  # --- Error terms（各変数に独立した乱数シードを設定）---
  set.seed(seed)     ; e0 <- runif(n)
  set.seed(seed + 1L); e1 <- runif(n)
  set.seed(seed + 2L); e2 <- runif(n)
  set.seed(seed + 3L); e3 <- runif(n)
  set.seed(seed + 4L); e4 <- runif(n)
  set.seed(seed + 5L); e5 <- runif(n)
  set.seed(seed + 6L); e6 <- runif(n)
  set.seed(seed + 7L); e7 <- runif(n)
  set.seed(seed + 8L); e8 <- runif(n)
  set.seed(seed + 9L); e9 <- runif(n)

  # --- Data generation（因果順序に従う）---
  x3 <- e3
  x0 <- 3.0 * x3 + e0
  x2 <- 6.0 * x3 + e2
  x1 <- 3.0 * x0 + 2.0 * x2 + e1
  x5 <- 4.0 * x0 + e5
  x4 <- 8.0 * x0 - 1.0 * x2 + e4
  x6 <- 2.0 * x1 + e6
  x7 <- 1.5 * x4 + 3.0 * x0 + e7
  x8 <- 0.5 * x2 + 2.0 * x5 + e8
  x9 <- 7.0 * x3 + 1.0 * x6 + e9

  return(
    data.frame(x0 = x0, x1 = x1, x2 = x2, x3 = x3, x4 = x4,
               x5 = x5, x6 = x6, x7 = x7, x8 = x8, x9 = x9)
  )
  }


#' True adjacency matrix for 10-variable sample
#'
#' @param labels variable names (default: x0-x9)
#' @return true adjacency matrix (10 x 10)
#' @export
true_adjacency_matrix_10 <- function(labels = paste0("x", 0:9)) {
  m <- matrix(0, nrow = 10, ncol = 10,
              dimnames = list(labels, labels))

  # [row=to, col=from] = coefficient
  m["x0", "x3"] <-  3.0
  m["x2", "x3"] <-  6.0
  m["x9", "x3"] <-  7.0
  m["x1", "x0"] <-  3.0
  m["x5", "x0"] <-  4.0
  m["x4", "x0"] <-  8.0
  m["x7", "x0"] <-  3.0
  m["x1", "x2"] <-  2.0
  m["x4", "x2"] <- -1.0
  m["x8", "x2"] <-  0.5
  m["x6", "x1"] <-  2.0
  m["x8", "x5"] <-  2.0
  m["x7", "x4"] <-  1.5
  m["x9", "x6"] <-  1.0

  return(m)
}
